stages:
  - test
  - build
  - deploy

image: python:3.12

variables:
  DJANGO_SETTINGS_MODULE: oc_lettings_site.settings
  PYTHONPATH: "$CI_PROJECT_DIR"

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - flake8 . # || echo "Flake8 non bloquant"
    - pytest --cov=letting --cov=profiles --cov=oc_lettings_site --cov-report=term-missing --cov-fail-under=80

build_and_push:
  needs: [test]
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build --build-arg COMMIT_HASH=$CI_COMMIT_SHORT_SHA -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
    - |
      echo "🔍 Inspecting built image label:"
      docker inspect $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA --format='🔗 Commit embedded in image: {{ index .Config.Labels "git_commit" }}'
  only:
    - master

deploy_to_render:
  needs: [build_and_push]
  stage: deploy
  script:
    - curl -X POST "$RENDER_DEPLOY_HOOK"
  only:
    - master