stages:
  - test
  - build
  - deploy

image: python:3.12

variables:
  DJANGO_SETTINGS_MODULE: oc_lettings_site.settings
  PYTHONPATH: "$CI_PROJECT_DIR"

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - flake8 . || echo "Flake8 non bloquant"
    - pytest --cov=letting --cov=profiles --cov=oc_lettings_site --cov-report=term-missing

build_and_push:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_USERNAME/p13-docker:latest .
    - docker tag $DOCKER_USERNAME/p13-docker:latest $DOCKER_USERNAME/p13-docker:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_USERNAME/p13-docker:latest
  only:
    - master

deploy_to_render:
  stage: deploy
  script:
    - curl -X POST "$RENDER_DEPLOY_HOOK"
  only:
    - master