[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ocp13"
version = "1.0.0"
description = "Documentation for the OCP13 Django project"
authors = [
  { name="Sally PJ" }
]
dependencies = []