# Generated by Django 3.0 on 2025-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0002_auto_20250317_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
